#!/bin/bash
# Remote setup script generated by Antigravity
# Variables from .env
USER="imobiledesigns-betadrop"
DOMAIN="betadrop.app"
REMOTE_PATH="/home/$USER/htdocs/$DOMAIN"
TAR_FILE="betadrop_deploy.tar.gz"

# Create project directory
mkdir -p $REMOTE_PATH

# Move and extract
if [ -f "$TAR_FILE" ]; then
    mv "$TAR_FILE" "$REMOTE_PATH/"
fi

cd "$REMOTE_PATH"

if [ -f "$TAR_FILE" ]; then
    tar -xzf "$TAR_FILE"
    rm "$TAR_FILE"
fi

# Ensure Node.js and PM2 are available
export PATH=$PATH:/usr/local/bin:/usr/bin

# Install dependencies
echo "📥 Installing dependencies..."
npm install

# Setup .env
echo "📝 Configuring .env on server..."
if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
    else
        echo "WARNING: .env.example not found"
    fi
fi

# Update/Inject production credentials
sed -i "s|DATABASE_URL=.*|DATABASE_URL=mysql://betadrop:3asJGfsQtl5Y0416Z06T@localhost:3306/betadrop|g" .env
sed -i "s|NEXT_PUBLIC_APP_URL=.*|NEXT_PUBLIC_APP_URL=https://betadrop.app|g" .env

# SMTP Configuration
sed -i "s|SMTP_HOST=.*|SMTP_HOST=\"smtp.gmail.com\"|g" .env
sed -i "s|SMTP_PORT=.*|SMTP_PORT=\"587\"|g" .env
sed -i "s|SMTP_SECURE=.*|SMTP_SECURE=\"false\"|g" .env
sed -i "s|SMTP_USER=.*|SMTP_USER=\"alerts@imobiledesigns.com\"|g" .env
sed -i "s|SMTP_PASS=.*|SMTP_PASS=\"ctxdlzlstzrvdema\"|g" .env
sed -i "s|SMTP_FROM=.*|SMTP_FROM=\"BetaDrop <alerts@imobiledesigns.com>\"|g" .env

# Only set JWT_SECRET if not already set or if it's the dev one
if grep -q "JWT_SECRET=dev-secret-key" .env || ! grep -q "JWT_SECRET=" .env; then
    sed -i "s|JWT_SECRET=.*|JWT_SECRET=$(openssl rand -base64 32)|g" .env
fi

# Ensure PORT is set
if ! grep -q "PORT=3001" .env; then
    echo "PORT=3001" >> .env
fi

# Set WebAuthn RP_ID for passkeys
if ! grep -q "WEBAUTHN_RP_ID=" .env; then
    echo "WEBAUTHN_RP_ID=betadrop.app" >> .env
fi

# Initialize database and sync new tables
echo "🗄️ Initializing database..."
if [ -f "scripts/init-db.sql" ]; then
    mysql -u betadrop -p'3asJGfsQtl5Y0416Z06T' betadrop < scripts/init-db.sql || echo "⚠️  DB Init skipped"
fi

echo "🔄 Syncing new tables..."
if [ -f "scripts/sync-production.sql" ]; then
    mysql -u betadrop -p'3asJGfsQtl5Y0416Z06T' betadrop < scripts/sync-production.sql || echo "⚠️  Sync skipped"
fi

# Build the project
echo "🏗️ Building Next.js application..."
npm run build

# Create storage directory
mkdir -p storage/ios storage/android

# Start application
echo "🔄 Starting application on port 3001..."

# Kill any existing process
pkill -f "$REMOTE_PATH/server.js" || true
pkill -f "node server.js" || true

# Run server
if [ -f "server.js" ]; then
    nohup env PORT=3001 node server.js > app.log 2>&1 &
else
    nohup env PORT=3001 npm start > app.log 2>&1 &
fi

echo "🚀 Server is running. Check app.log."
